const ACTION_TYPES = {
    FETCH_PHONES_REQUEST: "FETCH_PHONES_REQUEST",
    FETCH_PHONES_SUCCESS: "FETCH_PHONES_SUCCESS",
    FETCH_PHONES_FAILURE: "FETCH_PHONES_FAILURE",
}

export default ACTION_TYPES;