const ACTIONS = {
    FETCH_NOTES_REQUEST: "FETCH_NOTES_REQUEST",
    FETCH_NOTES_SUCCESS: "FETCH_NOTES_SUCCESS",
    FETCH_NOTES_FAILURE: "FETCH_NOTES_FAILURE",

    CREATE_NOTE_REQUEST: "CREATE_NOTE_REQUEST",
    CREATE_NOTE_SUCCESS: "CREATE_NOTE_SUCCESS",
    CREATE_NOTE_FAILURE: "CREATE_NOTE_FAILURE",

    REMOVE_NOTE_REQUEST: "REMOVE_NOTE_REQUEST",
    REMOVE_NOTE_SUCCESS: "REMOVE_NOTE_SUCCESS",
    REMOVE_NOTE_FAILURE: "REMOVE_NOTE_FAILURE",
}

export default ACTIONS;