const ACTION_TYPES = {
    FETCH_PHONES_REQUEST:       "FETCH_PHONES_REQUEST",
    FETCH_PHONES_SUCCESS:       "FETCH_PHONES_SUCCESS",
    FETCH_PHONES_FAILURE:       "FETCH_PHONES_FAILURE",

    LOAD_MORE_PHONES_REQUEST:   "LOAD_MORE_PHONES_REQUEST",
    LOAD_MORE_PHONES_SUCCESS:   "LOAD_MORE_PHONES_SUCCESS",
    LOAD_MORE_PHONES_FAILURE:   "LOAD_MORE_PHONES_FAILURE",

    FETCH_CATEGORIES_REQUEST:   "FETCH_CATEGORIES_REQUEST",
    FETCH_CATEGORIES_SUCCESS:   "FETCH_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_FAILURE:   "FETCH_CATEGORIES_FAILURE",

    FETCH_PHONE_BY_ID_REQUEST:  "FETCH_PHONE_BY_ID_REQUEST",
    FETCH_PHONE_BY_ID_SUCCESS:  "FETCH_PHONE_BY_ID_SUCCESS",
    FETCH_PHONE_BY_ID_FAILURE:  "FETCH_PHONE_BY_ID_FAILURE",

    ADD_PHONE_TO_BASKET:        "ADD_PHONE_TO_BASKET",
    REMOVE_PHONE_TO_BASKET:     "REMOVE_PHONE_TO_BASKET",
    CLEAN_BASKET:               "CLEAN_BASKET",

    SEARCH_PHONE:               "SEARCH_PHONE"
}

export default ACTION_TYPES;